# Generated by Django 5.0.1 on 2024-01-22 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_chat.createchat')),
            ],
        ),
    ]
