# Generated by Django 5.0.1 on 2024-01-22 02:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_member_1', models.CharField(max_length=100)),
                ('chat_member_2', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
